=== ReliSA/IMiGEr/sources/backend/imiger-core/src/main/webapp/imiger-raw-input-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "http://example.com/product.schema.json",
	"title": "IMiGEr - raw input schema",
	"description": "Diagram displayable by IMiGEr tool using raw input",
	"type": "object",
	"properties": {
		"attributeTypes": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"dataType": {
						"type": "string"
					},
					"name": {
						"type": "string"
					},
					"text": {
						"type": "string"
					}
				},
				"required": [ "dataType", "name" ]
			},
			"uniqueItems": true
		},
		"edgeArchetypes": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"text": {
						"type": "string"
					}
				},
				"required": [ "name" ]
			},
			"uniqueItems": true
		},
		"vertexArchetypes": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"icon": {
						"type": "string"
					},
					"name": {
						"type": "string"
					},
					"text": {
						"type": "string"
					}
				},
				"required": [ "name" ]
			},
			"uniqueItems": true
		},
		"vertices": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"archetype": {
						"type": "integer",
						"minimum": 0
					},
					"attributes": {
						"type": "array",
						"items": {
							"type": "array",
							"minItems": 2,
							"maxItems": 2
						}
					},
					"id": {
						"type": "integer"
					},
					"name": {
						"type": "string"
					},
					"text": {
						"type": "string"
					},
					"position": {
						"anyOf": [
							{
								"type": "object",
								"properties": {
									"x": {
										"type": "number"
									},
									"y": {
										"type": "number"
									}
								},
								"required": [ "x", "y" ]
							}, {
								"type": "null"
							}
						]
					}
				},
				"required": [ "id", "name" ]
			},
			"minItems": 1,
			"uniqueItems": true
		},
		"edges": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"subedgeInfo": {
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"id": {
									"type": "integer"
								},
								"archetype": {
									"type": "integer",
									"minimum": 0
								},
								"attributes": {
									"type": "array",
									"items": {
										"type": "array",
										"minItems": 2,
										"maxItems": 2
									}
								}
							},
							"required": [ "id", "archetype", "attributes" ]
						}
					},
					"id": {
						"type": "integer"
					},
					"text": {
						"type": "string"
					},
					"from": {
						"type": "integer"
					},
					"to": {
						"type": "integer"
					}
				},
				"required": [ "subedgeInfo", "id", "from", "to" ]
			},
			"minItems": 1,
			"uniqueItems": true
		},
		"possibleEnumValues": {
			"type": "object"
		},
		"groups": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"id": {
						"type": "integer"
					},
					"name": {
						"type": "string"
					},
					"verticesId": {
						"type": "array",
						"items": {
							"type": "integer"
						},
						"minItems": 1
					},
					"verticesEdgeFromId": {
						"type": "array",
						"items": {
							"type": "integer"
						}
					},
					"verticesEdgeToId": {
						"type": "array",
						"items": {
							"type": "integer"
						}
					},
					"position": {
						"anyOf": [
							{
								"type": "object",
								"properties": {
									"x": {
										"type": "number"
									},
									"y": {
										"type": "number"
									}
								},
								"required": [ "x", "y" ]
							}, {
								"type": "null"
							}
						]
					}
				},
				"required": [ "id", "name", "verticesId" ]
			},
			"uniqueItems": true
		},
		"sideBar": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"id": {
						"type": "string",
						"pattern": "^(group|vertex)-[0-9]+$"
					}
				},
				"required": [ "id" ]
			},
			"uniqueItems": true
		},
		"highlightedVertex": {
			"type": "string"
		},
		"highlightedEdge": {
			"type": "string"
		}
	},
	"required": [ "vertices", "edges" ]
}

=== ReliSA/IMiGEr/examples/IMiGEr_RAW_json/simple-2-group.json
{
  "attributeTypes": [],
  "edgeArchetypes": [
    {
      "name": "edge",
      "text": ""
    }
  ],
  "vertexArchetypes": [
    {
      "icon": "",
      "name": "1",
      "text": ""
    },
    {
      "icon": "",
      "name": "2",
      "text": ""
    },
    {
      "icon": "",
      "name": "3",
      "t[ext": ""
    },
    {
      "icon": "",
      "name": "4",
      "text": ""
    }
  ],
  "vertices": [
    {
      "archetype": 0,
      "attributes": [],
      "id": 1,
      "text": "",
      "name": "V1",
      "position": {
        "x": 1030,
        "y": 661
      }
    },
    {
      "archetype": 1,
      "attributes": [],
      "id": 2,
      "text": "",
      "name": "V2",
      "position": {
        "x": 985,
        "y": 871
      }
    },
    {
      "archetype": 1,
      "attributes": [],
      "id": 3,
      "text": "",
      "name": "V3",
      "position": {
        "x": 1088,
        "y": 416
      }
    },
    {
      "archetype": 3,
      "attributes": [],
      "id": 4,
      "text": "",
      "name": "V4",
      "position": {
        "x": 635,
        "y": 439
      }
    },
    {
      "archetype": 2,
      "attributes": [],
      "id": 5,
      "text": "",
      "name": "V5",
      "position": {
        "x": 609,
        "y": 758
      }
    }
  ],
  "edges": [
    {
      "subedgeInfo": [
        {
          "archetype": 0,
          "attributes": [],
          "id": 0
        }
      ],
      "from": 1,
      "to": 2,
      "text": "",
      "id": 1
    },
    {
      "subedgeInfo": [
        {
          "archetype": 0,
          "attributes": [],
          "id": 4
        }
      ],
      "from": 4,
      "to": 5,
      "text": "",
      "id": 2
    },
    {
      "subedgeInfo": [
        {
          "archetype": 0,
          "attributes": [],
          "id": 2
        }
      ],
      "from": 1,
      "to": 4,
      "text": "",
      "id": 3
    },
    {
      "subedgeInfo": [
        {
          "archetype": 0,
          "attributes": [],
          "id": 1
        }
      ],
      "from": 3,
      "to": 1,
      "text": "",
      "id": 4
    },
    {
      "subedgeInfo": [
        {
          "archetype": 0,
          "attributes": [],
          "id": 3
        }
      ],
      "from": 4,
      "to": 1,
      "text": "",
      "id": 5
    }
  ],
  "possibleEnumValues": {},
  "groups": [
    {
      "id": 3,
      "name": "Group X",
      "verticesId": [
        2,
        3,
        5
      ],
      "verticesEdgeFromId": [],
      "verticesEdgeToId": [],
      "position": {
        "x": 701,
        "y": 777
      }
    }
  ],
  "sideBar": [],
  "highlightedVertex": "",
  "highlightedEdge": ""
}

=== ReliSA/IMiGEr/examples/IMiGEr_RAW_json/simple-1.json
{
  "attributeTypes": [
    {
      "dataType": "STRING",
      "name": "D",
      "text": "0"
    },
    {
      "dataType": "STRING",
      "name": "C",
      "text": "1"
    },
    {
      "dataType": "STRING",
      "name": "B",
      "text": "2"
    },
    {
      "dataType": "STRING",
      "name": "A",
      "text": "3"
    }
  ],
  "edgeArchetypes": [
    {
      "name": "edgeArchetype1",
      "text": ""
    },
    {
      "name": "edgeArchetype2",
      "text": ""
    }
  ],
  "vertexArchetypes": [
    {
      "icon": "",
      "name": "1",
      "text": ""
    },
    {
      "icon": "",
      "name": "2",
      "text": ""
    },
    {
      "icon": "",
      "name": "3",
      "text": ""
    }
  ],
  "vertices": [
    {
      "archetype": 2,
      "attributes": [
        [
          "D",
          "E"
        ],
        [
          "B",
          "W"
        ],
        [
          "A",
          "Q"
        ]
      ],
      "id": 1,
      "text": "",
      "name": "V1",
      "position": {
        "x": 753.25,
        "y": 693.75
      }
    },
    {
      "archetype": 1,
      "attributes": [
        [
          "D",
          "E"
        ],
        [
          "C",
          "Q"
        ],
        [
          "B",
          "W"
        ]
      ],
      "id": 2,
      "text": "",
      "name": "V2",
      "position": {
        "x": 534.25,
        "y": 897.5
      }
    },
    {
      "archetype": 0,
      "attributes": [
        [
          "D",
          "Q"
        ],
        [
          "C",
          "W"
        ],
        [
          "A",
          "E"
        ]
      ],
      "id": 3,
      "text": "",
      "name": "V3",
      "position": {
        "x": 961.25,
        "y": 899.75
      }
    }
  ],
  "edges": [
    {
      "subedgeInfo": [
        {
          "archetype": 0,
          "attributes": [
            [
              "D",
              "E"
            ],
            [
              "C",
              "W"
            ]
          ],
          "id": 3
        }
      ],
      "from": 1,
      "to": 3,
      "text": "",
      "id": 1
    },
    {
      "subedgeInfo": [
        {
          "archetype": 0,
          "attributes": [
            [
              "D",
              "E"
            ],
            [
              "B",
              "W"
            ],
            [
              "A",
              "Q"
            ]
          ],
          "id": 1
        },
        {
          "archetype": 1,
          "attributes": [
            [
              "D",
              "D"
            ],
            [
              "B",
              "S"
            ],
            [
              "A",
              "A"
            ]
          ],
          "id": 2
        }
      ],
      "from": 1,
      "to": 2,
      "text": "",
      "id": 2
    },
    {
      "subedgeInfo": [
        {
          "archetype": 1,
          "attributes": [
            [
              "C",
              "T"
            ],
            [
              "B",
              "R"
            ]
          ],
          "id": 4
        }
      ],
      "from": 3,
      "to": 1,
      "text": "",
      "id": 3
    }
  ],
  "possibleEnumValues": {},
  "groups": [],
  "sideBar": [],
  "highlightedVertex": "",
  "highlightedEdge": ""
}

=== ReliSA/IMiGEr/sources/backend/imiger-dot-converter/src/test/resources/integrityTestResult.json
{"vertices":[{"attributes":[["test","test value"]],"id":0,"name":"A","archetype":0,"text":""},{"attributes":[["test","test value"]],"id":1,"name":"B","archetype":0,"text":""}],"edges":[{"subedgeInfo":[{"archetype":0,"id":0,"attributes":[["test","test value"]]}],"id":0,"from":0,"to":1,"text":"A-B"}],"vertexArchetypes":[{"name":"Vertex","text":"","icon":""}],"edgeArchetypes":[{"name":"Edge","text":""}],"attributeTypes":[{"name":"test","dataType":"STRING","text":""}],"possibleEnumValues":{},"groups":[],"sideBar":[],"highlightedVertex":"","highlightedEdge":""}

=== ReliSA/IMiGEr/examples/IMiGEr_RAW_json/simple-icons.json
{
  "attributeTypes": [],
  "edgeArchetypes": [
    {
      "name": "edge",
      "text": ""
    }
  ],
  "vertexArchetypes": [
    {
      "icon": "<rect class=\"testingArchetypeIcon\" width=\"12\" height=\"15\" x=\"0\" y =\"0\" stroke=\"none\" fill=\"green\"/>",
      "name": "SpecifiedIcon",
      "text": ""
    },
    {
      "icon": "",
      "name": "UnspecifiedIcon",
      "text": ""
    },
    {
      "icon": "<text y=\"8\" fill=\"red\">â˜º</text>",
      "name": "Smiley",
      "text": ""
    }
  ],
  "vertices": [
    {
      "archetype": 0,
      "attributes": [],
      "id": 1,
      "text": "",
      "name": "Vertex with specified icon",
      "position": {
        "x": 640.5,
        "y": 408.25
      }
    },
    {
      "archetype": 1,
      "attributes": [],
      "id": 2,
      "text": "",
      "name": "Vertex with unspecified icon",
      "position": {
        "x": 826.25,
        "y": 536.75
      }
    },
    {
      "archetype": 2,
      "attributes": [],
      "id": 3,
      "text": "",
      "name": "Vertex with smiley as archetype icon",
      "position": {
        "x": 438,
        "y": 537.75
      }
    }
  ],
  "edges": [
    {
      "subedgeInfo": [
        {
          "archetype": 0,
          "attributes": [],
          "id": 1
        }
      ],
      "from": 1,
      "to": 3,
      "text": "",
      "id": 1
    },
    {
      "subedgeInfo": [
        {
          "archetype": 0,
          "attributes": [],
          "id": 0
        }
      ],
      "from": 1,
      "to": 2,
      "text": "",
      "id": 2
    }
  ],
  "possibleEnumValues": {},
  "groups": [],
  "sideBar": [],
  "highlightedVertex": "",
  "highlightedEdge": ""
}

=== ReliSA/IMiGEr/examples/IMiGEr_RAW_json/simple-2.json
{
  "attributeTypes": [],
  "edgeArchetypes": [
    {
      "name": "edge",
      "text": ""
    }
  ],
  "vertexArchetypes": [
    {
      "icon": "",
      "name": "1",
      "text": ""
    },
    {
      "icon": "",
      "name": "2",
      "text": ""
    },
    {
      "icon": "",
      "name": "3",
      "text": ""
    },
    {
      "icon": "",
      "name": "4",
      "text": ""
    }
  ],
  "vertices": [
    {
      "archetype": 0,
      "attributes": [],
      "id": 1,
      "text": "",
      "name": "V1",
      "position": {
        "x": 989.5,
        "y": 684
      }
    },
    {
      "archetype": 1,
      "attributes": [],
      "id": 2,
      "text": "",
      "name": "V2",
      "position": {
        "x": 985.75,
        "y": 871.5
      }
    },
    {
      "archetype": 1,
      "attributes": [],
      "id": 3,
      "text": "",
      "name": "V3",
      "position": {
        "x": 988,
        "y": 540
      }
    },
    {
      "archetype": 3,
      "attributes": [],
      "id": 4,
      "text": "",
      "name": "V4",
      "position": {
        "x": 694,
        "y": 678.25
      }
    },
    {
      "archetype": 2,
      "attributes": [],
      "id": 5,
      "text": "",
      "name": "V5",
      "position": {
        "x": 702.75,
        "y": 755
      }
    }
  ],
  "edges": [
    {
      "subedgeInfo": [
        {
          "archetype": 0,
          "attributes": [],
          "id": 0
        }
      ],
      "from": 1,
      "to": 2,
      "text": "",
      "id": 1
    },
    {
      "subedgeInfo": [
        {
          "archetype": 0,
          "attributes": [],
          "id": 4
        }
      ],
      "from": 4,
      "to": 5,
      "text": "",
      "id": 2
    },
    {
      "subedgeInfo": [
        {
          "archetype": 0,
          "attributes": [],
          "id": 2
        }
      ],
      "from": 1,
      "to": 4,
      "text": "",
      "id": 3
    },
    {
      "subedgeInfo": [
        {
          "archetype": 0,
          "attributes": [],
          "id": 1
        }
      ],
      "from": 3,
      "to": 1,
      "text": "",
      "id": 4
    },
    {
      "subedgeInfo": [
        {
          "archetype": 0,
          "attributes": [],
          "id": 3
        }
      ],
      "from": 4,
      "to": 1,
      "text": "",
      "id": 5
    }
  ],
  "possibleEnumValues": {},
  "groups": [],
  "sideBar": [],
  "highlightedVertex": "",
  "highlightedEdge": ""
}
